name: Deploy and test cluster

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Cluster identifier'
        default: 'c111'
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    outputs:
      cluster_id: ${{ steps.deployment.outputs.cluster_id }}
      cluster_ip: ${{ steps.deployment.outputs.cluster_ip }}
      cluster_secret: ${{ steps.deployment.outputs.cluster_secret }}

    steps:
    - name: Checkout sbcli
      uses: actions/checkout@v4
      with:
        path: sbcli

    - name: Checkout deployment tooling
      uses: actions/checkout@v4
      with:
        repository: simplyblock-io/simplyBlockDeploy
        path: deploy
        ref: deployment-test

    - name: Deploy cluster
      id: deployment
      run: |
        cd deploy
        if [[ "${{github.ref}}" == refs/pull/* ]]; then
          tag=${GITHUB_REF/\/merge/}
          TAG=$(echo pr-${tag:10})
        else
          TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')
        fi
        eval $(python3 inventory.py inventory/${{ github.event.inputs.cluster }}.yml)
        export NDCS=1
        export NPCS=1
        export BS=4096
        export CHUNK_BS=4096
        export NR_HUGEPAGES=2048
        export SBCLI_INSTALL_SOURCE=${{ github.repositoryUrl }}@${{ github.sha }}
        export SIMPLY_BLOCK_DOCKER_IMAGE=public.ecr.aws/simply-block/simplyblock:$TAG
        ./bootstrap-cluster.sh --max-lvol 10 --max-snap 10 --max-size 400G --number-of-devices 1 --sbcli-cmd sbcli-dev --spdk-debug

  test:
    runs-on: self-hosted
    needs: deploy

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        pytest simplyblock_web \
          --entrypoint=${{ needs.deploy.outputs.cluster_ip }} \
          --cluster=${{ needs.deploy.outputs.cluster_id }} \
          --secret=${{ needs.deploy.outputs.cluster_secret }}
